/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    EditorPanel: typeof import('./src/components/EditorPanel.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputText: typeof import('primevue/inputtext')['default']
    NewFileDialog: typeof import('./src/components/NewFileDialog.vue')['default']
    OutputPanel: typeof import('./src/components/OutputPanel.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    PopoverComponent: typeof import('./src/components/PopoverComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TopMenu: typeof import('./src/components/TopMenu.vue')['default']
  }
}
