services:
  dind:
    image: docker:27-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command: [ "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock" ]
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:2375/version" ]
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - dind-storage:/var/lib/docker
      - shared-code:/code   # 👈 шарим том для исходников

  compiler-api:
    build: .
    depends_on:
      dind:
        condition: service_healthy
    environment:
      DOCKER_HOST: tcp://dind:2375
      CODE_DIR: /code        # 👈 говорим API класть сюда файлы
    volumes:
      - shared-code:/code    # 👈 тот же том подключаем сюда
    ports:
      - "8080:8080"

volumes:
  dind-storage:
  shared-code:
