spring:
  application:
    name: compiler

compiler:
  timeout:
    seconds: 20
  java:
    image: openjdk:17

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  show-actuator: true
  default-produces-media-type: application/json

logging:
  level:
    org:
      coderun:
        compiler:
          service:
            FileService: DEBUG





